# Generated by Django 6.0.2 on 2026-03-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at_project_status_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
